# Paths provided for triger and pr definition provide examples of definition.
trigger:
  branches:
    include:
    - main
    - develop
    - release/*
  paths:
    include:
    - Bratislava2024MobileApp/NeuroMediaMobileApp/**
    - Bratislava2024MobileApp/NeuroMediaMobileApp.UI.Tests/**
    - Bratislava2024/NeuroMedia.API/**
    - Bratislava2024/Neuromedia.API.Tests/**
    - Bratislava2024/NeuroMedia.Application/**
    - Bratislava2024/Neuromedia.Infrastructure/**
    - Bratislava2024/NeuroMedia.Persistence/**
    exclude:
    - README.md
    - docs/**

pr:
  branches:
    include:
    - main
    - develop
    - release/*
  
  drafts: false
  
  paths:
    include:
    - Bratislava2024MobileApp/NeuroMediaMobileApp/**
    - Bratislava2024MobileApp/NeuroMediaMobileApp.UI.Tests/**
    - Bratislava2024/NeuroMedia.API/**
    exclude:
    - README.md
    - docs/**

pool:
  vmImage: 'windows-latest' # Windows required for MAUI

variables:
  # Configure pipeline variables and provide your values for empty variables
  # Build configuration variables 
  buildConfiguration: 'Release'
  dotnetVersion: '8.x'
  solutionPath: 'Bratislava2024MobileApp/NeuroMediaMobileApp.sln' # Example format, adjust for specific project

  # Sonar Cloud configuration variables
  sonarConnection: ''
  sonarProjectKey: ''
  sonarProjectName: ''
  sonarOrganization: ''

stages:
  - stage: Build
    displayName: 'Build and Analyze'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test Job'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET SDK $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'

          - task: CmdLine@2
            displayName: 'Install Maui Workload'
            inputs:
              script: 'dotnet workload install maui'

          - task: SonarCloudPrepare@4
            displayName: 'Prepare SonarCloud Analysis'
            inputs:
              SonarCloud: '$(sonarConnection)'
              organization: '$(sonarOrganization)'
              scannerMode: 'dotnet'
              projectKey: '$(sonarProjectKey)'
              projectName: '$(sonarProjectName)'

          - script: dotnet build $(solutionPath) --configuration $(buildConfiguration)
            displayName: 'Build Solution'

          - task: DotNetCoreCLI@2
            displayName: 'Test with Coverage'
            inputs:
              command: 'test'
              projects: '**/*Tests/*.csproj'
              arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage"'

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
            condition: always()

          - task: SonarCloudAnalyze@4
            displayName: 'Run SonarCloud Analysis'

          - task: SonarCloudPublish@4
            inputs:
              pollingTimeoutSec: '300'

          - template: templates/sonar-report.yml
